### PR TITLE
release prep

### PR DESCRIPTION
**Pull request by FredericBlum**
The usual release prep. Note that we do not currently have this conceptlist in Concepticon apparently. MAYBE all of the concepts are part of Scarborough-200, but in the lexibank-script it is called 'JenaFInal170'. @Bibiko @LinguList Maybe one of you has insights on this?

### CODE REVIEW

**Review by chrzyki — COMMENTED** [review]
Thanks! Good to wait for feedback on this by @Bibiko and @LinguList. Release prep looks good. What's the reason for the changes in the `ParameterTable`?

**Comment by FredericBlum** [comment]
@LinguList @Bibiko This PR got probably flooded in the github commits. Do we have insights on the conceptlist used?

**Comment by LinguList** [comment]
I do not know if we HAVE added it. But it was published [here](https://concepticon.clld.org/contributions/Heggarty-2020-200).

**Comment by LinguList** [comment]
If it diverges from that, we have to fix manually, since this is an official publication BASED on IECOR etc.

**Comment by LinguList** [comment]
They tweaked the concepts several times, so the official 200 item list is probably the one I mentioned before in my comment.

**Comment by chrzyki** [comment]
Also the sources are unmapped and only in https://github.com/lexibank/iecor/blob/master/raw/source.csv not `source.bib`.

**Comment by Bibiko** [comment]
• Re concept list,
as @LinguList mentioned the parameter list is based on Heggarty 2020-200 but was downsized to 170.
• Re sources,
as far as I can remember https://github.com/lexibank/iecor/blob/master/raw/source.csv is the 'old' source list used by IELex. All sources which are used for the cognate judgement etc. are in [https://github.com/lexibank/iecor/blob/master/cldf/sources.bib](https://github.com/lexibank/iecor/blob/master/cldf/sources.bib).

• What's the reason for the changes in the `ParameterTable`?

**Comment by FredericBlum** [comment]
The changes in the ParameterTable comes through the re-creating of the cldf-set, so I guess some change in the original data? This is nothing that came through other changes, and only refers to the examples for each concept, no the concept information itself

**Pull request merged**
